project_id = "ccwfazfmmhinjttskhrr"

[functions.get-guests]
verify_jwt = false

[functions.get-gallery]
verify_jwt = false

[functions.upload-photo]
verify_jwt = false

[functions.save-rsvp]
verify_jwt = false

[functions.test-token]
verify_jwt = false